project_id = "affable-operand-420317"
region     = "us-central1"
ent_terraform = "entrada_terraform1"
schema_bucket = "entrada_schema_bucket"
entrada_manual = "entrada_manual"
entrada_auto = "entrada_auto"
