project_id = "affable-operand-420317"
region     = "us-central1"
ent_terraform = "entrada_terraform1"
schema_bucket = "entrada_schema_bucket1"
entrada_manual = "entrada_manual1"
entrada_auto = "entrada_auto1"
